title: Michael Nims # your name (or website title) here
logo: "/images/Military headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an Army Reserve Captain with five years of service in military intelligence.I am capable leader, able to use critical thinking to efficiently solve complex problems and achieve shared goals. I am a hard-working, dedicated, and enthusiastic employee. I excel in teaching and mentoring others, fostering teamwork, and encouraging a positive work environment.
  <br><br>
  Web links 
  <br><br>
  <a href="https://www.linkedin.com/in/michael-nims-a7931b1b0/">Michael Nims LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/MikeNims/GIS_Portfolio">Michael Nims GIS File Repository</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
